### ISSUE TITLE
what ‘s wrong？

### ISSUE THREAD

**Issue by imac8t** [KarolAltamirano/generator-react-web#17]
src/App.js:22
 22: function render(Component: any, store: Store) {
                                            ^^^^^ identifier `Store`. Could not resolve name

src/store/configureStore.js:17
 17: export default function configureStore(initialState?: Object): Store {
                                                                    ^^^^^ identifier `Store`. Could not resolve name

test/example.spec.js:10
 10: describe('Example test', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

test/example.spec.js:21
 21:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

test/example.spec.js:25
 25:   it('should run successfully', () => {
       ^^ identifier `it`. Could not resolve name

teste2e/example.spec.e2e.js:6
  6: describe('Page', () => {

Found 9 errors
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! l-react@0.0.0 start: `yarn run check:all && cross-env NODE_ENV=development babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the l-react@0.0.0 start script 'yarn run check:all && cross-env NODE_ENV=development babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the l-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yarn run check:all && cross-env NODE_ENV=development babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs l-react
npm ERR! Or if that isn't available, you can get their info via:

**Comment by KarolAltamirano** [comment]
Try to do following steps:
1. make sure you have `flow-typed` installed (if not run `npm install -g flow-typed`)
2. remove `flow-typed` directory from root folder of the project if it exists
3. run `flow-typed install`
4. run `yarn run flow -- stop`
5. run `yarn run start`

**Comment by KarolAltamirano** [comment]
Closing this issue, please comment here if the provided steps doesn't solve the issue.
