### ISSUE TITLE
Any plans to upgrade to webpack2 ?

### ISSUE THREAD

**Issue by bernalrs** [KarolAltamirano/generator-react-web#7]
Would be nice to upgrade project dependencies to their latest respective versions.

**Comment by KarolAltamirano** [comment]
Hi @bernalrs, thank you for your question. Definitely, I am planning to upgrade to webpack 2. But as webpack is 'heart' of the boilerplate and there are probably more breaking changes in webpack 2 I don't wanna rush it. First I need to find time to check documentation of webpack 2, then rewrite configuration files and test everything properly so I can be sure that everything is working as expected (including HMR and so on).

Let's track process of upgrading to webpack 2 in this issue.

**Comment by bernalrs** [comment]
thanks for the update by the way I have found this post quite informative: https://github.com/webpack/webpack-cli/issues/6

**Comment by KarolAltamirano** [comment]
Great!!! Thanks for sharing

**Comment by KarolAltamirano** [comment]
New version with Webpack 2 released #9
